### ISSUE TITLE
gulp failing - fs.js:25, 'use strict'; ReferenceError: internalBinding is not defined

### ISSUE THREAD

**Issue by AaronNGray** [webcomponents/webcomponentsjs#1070]
Build is failing :-

```
C:\Users\aaron\GitHub\webcomponentsjs>npm run build

> @webcomponents/webcomponentsjs@2.1.3 build C:\Users\aaron\GitHub\webcomponentsjs
> gulp

fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1
    at req_ (C:\Users\aaron\GitHub\webcomponentsjs\node_modules\natives\index.js:137:5)
    at Object.req [as require] (C:\Users\aaron\GitHub\webcomponentsjs\node_modules\natives\index.js:54:10)
    at Object.<anonymous> (C:\Users\aaron\GitHub\webcomponentsjs\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @webcomponents/webcomponentsjs@2.1.3 build: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @webcomponents/webcomponentsjs@2.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aaron\AppData\Roaming\npm-cache\_logs\2019-02-25T17_40_33_695Z-debug.log

C:\Users\aaron\GitHub\webcomponentsjs>
```

**Comment by AaronNGray** [comment]
sorry old revision
