### ISSUE TITLE
4 tests fail for Microsoft Edge

### ISSUE THREAD

**Issue by rictic** [webcomponents/webcomponentsjs#363]
Microsoft's Edge browser is out as of today. Four webcomponentsjs tests currently fail. Relevent excerpts from the test:
### HTMLImports
- html/style-links.html

```
Error: AssertionError: expected 'transparent' to equal 'rgba(0, 0, 0, 0)' (http://10.0.1.87:8080/src/ShadowDOM/wrappers/events.js:242)
   at global.onerror (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:5738:7)
```
### Selection
- containsNode

```
AssertionError: expected true to be false
   at Assertion.prototype.assert (http://10.0.1.87:8080/tests/tools/chai/chai.js:921:7)
   at Anonymous function (http://10.0.1.87:8080/tests/tools/chai/chai.js:1235:5)
   at get to (http://10.0.1.87:8080/tests/tools/chai/chai.js:3668:9)
   at assert.isFalse (http://10.0.1.87:8080/tests/tools/chai/chai.js:2577:5)
   at Anonymous function (http://10.0.1.87:8080/tests/ShadowDOM/js/Selection.js:180:5)
   at callFn (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4338:5)
   at Runnable.prototype.run (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4331:7)
   at Runner.prototype.runTest (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4728:5)
   at Anonymous function (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4806:7)
   at next (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4653:7)
```
### Events
- retarget order

```
AssertionError: expected 'content, c, d, BUBBLING_PHASE' to equal undefined
   at Assertion.prototype.assert (http://10.0.1.87:8080/tests/tools/chai/chai.js:921:7)
   at assert.equal (http://10.0.1.87:8080/tests/tools/chai/chai.js:2437:5)
   at assertArrayEqual (http://10.0.1.87:8080/tests/ShadowDOM/tests.js:46:5)
   at Anonymous function (http://10.0.1.87:8080/tests/ShadowDOM/js/events.js:723:5)
   at callFn (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4338:5)
   at Runnable.prototype.run (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4331:7)
   at Runner.prototype.runTest (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4728:5)
   at Anonymous function (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4806:7)
   at next (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4653:7)
   at Anonymous function (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4663:7)
```
- retarget order (multiple shadow roots) 

```
AssertionError: expected 'content, c, d, BUBBLING_PHASE' to equal undefined
   at Assertion.prototype.assert (http://10.0.1.87:8080/tests/tools/chai/chai.js:921:7)
   at assert.equal (http://10.0.1.87:8080/tests/tools/chai/chai.js:2437:5)
   at assertArrayEqual (http://10.0.1.87:8080/tests/ShadowDOM/tests.js:46:5)
   at Anonymous function (http://10.0.1.87:8080/tests/ShadowDOM/js/events.js:842:5)
   at callFn (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4338:5)
   at Runnable.prototype.run (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4331:7)
   at Runner.prototype.runTest (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4728:5)
   at Anonymous function (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4806:7)
   at next (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4653:7)
   at Anonymous function (http://10.0.1.87:8080/tests/tools/mocha/mocha.js:4663:7)
```

**Comment by azakus** [comment]
I'm not super concerned about the HTMLImports bug. It may be that `transparent` and `rgba(0, 0, 0, 0)` are equivalent in Edge.

`containsNode` uses event path, so all three of the ShadowDOM bugs are related.

**Comment by TimvdLippe** [comment]
This is fixed along the way.
