### ISSUE TITLE
gulp build fails with latest npm dependencies

### ISSUE THREAD

**Issue by deiwin** [webcomponents/webcomponentsjs#572]
Starting from a clean clone, the following fails:

```
$ bower install
...
$ npm install
...
$ gulp build
[13:55:47] Using gulpfile ~/workspace/webcomponentsjs/gulpfile.js
[13:55:47] Starting 'version'...
[13:55:47] Starting 'copy-bower'...
[13:55:47] Finished 'version' after 38 ms
[13:55:47] Starting 'webcomponents-debug'...
[13:55:47] Starting 'webcomponents-lite-debug'...
[13:55:47] Starting 'CustomElements-debug'...
[13:55:47] Starting 'HTMLImports-debug'...
[13:55:47] Starting 'ShadowDOM-debug'...
[13:55:47] Starting 'MutationObserver-debug'...
fs.js:844
  return binding.lstat(pathModule._makeLong(path));
                                  ^

Error: ENOENT: no such file or directory, lstat '/Users/deiwin/workspace/webcomponentsjs/src/WeakMap/MutationObserver.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at DestroyableTransform.TransformStream [as _transform] (/Users/deiwin/workspace/webcomponentsjs/node_modules/gulp-header/index.js:38:12)
    at DestroyableTransform.Transform._read (/Users/deiwin/workspace/webcomponentsjs/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/deiwin/workspace/webcomponentsjs/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/deiwin/workspace/webcomponentsjs/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/deiwin/workspace/webcomponentsjs/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/deiwin/workspace/webcomponentsjs/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at DestroyableTransform.ondata (/Users/deiwin/workspace/webcomponentsjs/node_modules/gulp-uglify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:531:20)
    at emitOne (events.js:77:13)
```

Using the _exact_ versions specified in `package.json` (by removing the `^` from in front of the versions and running `npm install` again) fixes this issue. Presumably an update to one of the dependencies has broken the build process.

**Comment by notwaldorf** [comment]
Is this still reproducible, or can this be closed?

**Comment by deiwin** [comment]
Seems to be fixed. Thanks.
