### ISSUE TITLE
Version 2.1.0 and 2.1.1 Breaks Reflect Metadata's getMetadataKeys

### ISSUE THREAD

**Issue by alienriver49** [webcomponents/webcomponentsjs#998]
I'm using SystemJS (version 0.19.46) for the loading of the modules and files in my application, webcomponentsjs for support for native web components, and [reflect-metadata](https://github.com/rbuckton/reflect-metadata) (version 0.1.10) for supporting of metadata. If you need more information about technologies used, please let me know, though it seems pretty cut and dry.

It looks to stem from the overwriting of Object.keys in webcomponentsjs to filter out symbols, which Reflect uses down the line in the call to getMetadataKeys to get the keys which contain metadata (symbols). Here's the code below with the stack trace:

```
system-polyfills.src.js:145 Potentially unhandled rejection [1] TypeError
    at GetIterator (https://localhost/jspm_packages/npm/reflect-metadata@0.1.10/Reflect.js:823:19)
    at OrdinaryOwnMetadataKeys (https://localhost/jspm_packages/npm/reflect-metadata@0.1.10/Reflect.js:642:24)
    at OrdinaryMetadataKeys (https://localhost/jspm_packages/npm/reflect-metadata@0.1.10/Reflect.js:605:23)
    at OrdinaryMetadataKeys (https://localhost/jspm_packages/npm/reflect-metadata@0.1.10/Reflect.js:609:26)
    at OrdinaryMetadataKeys (https://localhost/jspm_packages/npm/reflect-metadata@0.1.10/Reflect.js:609:26)
    at OrdinaryMetadataKeys (https://localhost/jspm_packages/npm/reflect-metadata@0.1.10/Reflect.js:609:26)
    at Object.getMetadataKeys (https://localhost/jspm_packages/npm/reflect-metadata@0.1.10/Reflect.js:419:16)
    at eval (https://localhost/view-parser.ts!transpiled:182:45)
    at Array.forEach (<anonymous>)
    at ViewParser.parseNode (https://localhost/view-parser.ts!transpiled:180:59)
```

This seems to be an issue mainly with getMetadataKeys, but I imagine it could cause issues elsewhere as well.

**Comment by TimvdLippe** [comment]
We are spec-compliant by filtering out the `Symbol`s, so I think this is an issue in `reflect-metadata` instead. Could you link to the specific snippet that is causing problems?

**Comment by alienriver49** [comment]
The link to the line in reflect-metadata is:
https://github.com/rbuckton/reflect-metadata/blob/c2dbe1d02ceb9987f9002eedf0cdb21d74de0019/Reflect.js#L662

He's using a Map and it's .keys() method, so I actually don't think the issue is with overwriting Object.keys. The issue is occurring in the GetIterator method and seems to stem from looking up the iterator for the object using Symbol.iterator.

In webcomponentsjs 2.0.4, typing Symbol.iterator in the console returns `Symbol(Symbol.iterator)`.

In webcomponentsjs 2.1.1, typing Symbol.iterator in the console returns `String {"__symbol:iterator0.35411877404381921", constructor: ƒ}` and you can expand out the object.

It looks as though Symbol.iterator (and all Symbols at that) are being converted to String. I wonder if it's to do with that Symbol polyfill you guys are using? It looks like they have a few issues open on their Github dealing with Symbol.iterator.

Thanks for hearing me out and working through this with me.
